In [6]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt

In [7]:
data = pd.read_csv('/kaggle/input/mnist-in-csv/mnist_train.csv')

In [8]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_test = data[0:1000].T
Y_test = data_test[0]
X_test = data_test[1:n]
X_test = X_test / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [9]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z) / sum(np.exp(Z))

def forward_propagation(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot_encode(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def ReLU_dev(Z):
    return Z > 0

def back_propagation(Z1, A1, Z2, A2, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot_encode(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = (1 / m) * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * ReLU_dev(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [10]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_propagation(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_propagation(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if(i % 10 == 0):
            print("Iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [11]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.1)

Iteration:  0
[4 7 4 ... 2 0 8] [2 4 7 ... 0 8 8]
Accuracy:  0.14396610169491525
Iteration:  10
[4 7 4 ... 2 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.21128813559322035
Iteration:  20
[2 7 4 ... 2 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.2938135593220339
Iteration:  30
[2 7 4 ... 2 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.36954237288135594
Iteration:  40
[2 4 4 ... 2 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.4310677966101695
Iteration:  50
[2 4 4 ... 2 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.47989830508474574
Iteration:  60
[2 4 7 ... 0 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.5203728813559322
Iteration:  70
[2 4 7 ... 0 0 6] [2 4 7 ... 0 8 8]
Accuracy:  0.555864406779661
Iteration:  80
[2 4 7 ... 0 3 6] [2 4 7 ... 0 8 8]
Accuracy:  0.5870847457627119
Iteration:  90
[2 4 7 ... 0 3 6] [2 4 7 ... 0 8 8]
Accuracy:  0.6149152542372881
Iteration:  100
[2 4 7 ... 0 3 6] [2 4 7 ... 0 8 8]
Accuracy:  0.6375762711864407
Iteration:  110
[2 4 7 ... 0 3 8] [2 4 7 ... 0 8 8]
Accuracy:  0.6578135593220339
Iteration:  120
[2 4 7 .